{
  doTest(true,"Unable to inline outside try/catch statement");
}
