{
  try {
  }
 catch (  RuntimeException|MyException<caret> e) {
  }
}
