{
  boolean wasThrown=false;
  try {
    exceptionCase.tryClosure();
  }
 catch (  Throwable e) {
    if (shouldOccur) {
      wasThrown=true;
      final String errorMessage=exceptionCase.getAssertionErrorMessage();
      assertEquals(errorMessage,exceptionCase.getExpectedExceptionClass(),e.getClass());
      if (expectedErrorMsg != null) {
        assertEquals("Compare error messages",expectedErrorMsg,e.getMessage());
      }
    }
 else     if (exceptionCase.getExpectedExceptionClass().equals(e.getClass())) {
      wasThrown=true;
      System.out.println("");
      e.printStackTrace(System.out);
      fail("Exception isn't expected here. Exception message: " + e.getMessage());
    }
 else {
      throw e;
    }
  }
 finally {
    if (shouldOccur && !wasThrown) {
      fail(exceptionCase.getAssertionErrorMessage());
    }
  }
}
