{
  return "'#ref' inside 'catch' block ignores the caught exception #loc";
}
