{
  try {
    c.call();
  }
 catch (  Exception e) {
    throw new RuntimeException(e);
  }
}
