{
  try {
    return create(assertion,getExpected(assertion),getActual(assertion));
  }
 catch (  Throwable e) {
    return new ExceptionPacketFactory(PoolOfTestStates.FAILED_INDEX,assertion);
  }
}
