def recover(self):
    lock = self.lock()
    try:
        if os.path.exists(self.sjoin('journal')):
            self.ui.status(_('rolling back interrupted transaction\n'))
            transaction.rollback(self.sopener, self.sjoin('journal'), self.ui.warn)
            self.invalidate()
            return True
        else:
            self.ui.warn(_('no interrupted transaction available\n'))
            return False
    finally:
        lock.release()
