{
  try {
    g();
  }
 catch (  Exception e) {
  }
}
