{
  if (throwable instanceof InvocationTargetException)   throwable=throwable.getCause();
  return rethrowException(throwable);
}
