{
  try {
    myResult=doRun();
  }
 catch (  Throwable aThrowable) {
    myException=aThrowable;
  }
}
